wpsetup:
    path:  /
    defaults: { _controller: "ACSACSPanelWordpressBundle:WPSetup:index" }

wpsetup_show:
    path:  /{id}/show
    defaults: { _controller: "ACSACSPanelWordpressBundle:WPSetup:show" }

wpsetup_new:
    path:  /new
    defaults: { _controller: "ACSACSPanelWordpressBundle:WPSetup:new" }

wpsetup_create:
    path:  /create
    defaults: { _controller: "ACSACSPanelWordpressBundle:WPSetup:create" }
    requirements: { _method: post }

wpsetup_edit:
    path:  /{id}/edit
    defaults: { _controller: "ACSACSPanelWordpressBundle:WPSetup:edit" }

wpsetup_update:
    path:  /{id}/update
    defaults: { _controller: "ACSACSPanelWordpressBundle:WPSetup:update" }
    requirements: { _method: post }

wpsetup_delete:
    path:  /{id}/delete
    defaults: { _controller: "ACSACSPanelWordpressBundle:WPSetup:delete" }
    requirements: { _method: post }
