<?php


namespace ACS\ACSPanelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LogItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogItemRepository extends EntityRepository
{
}
