language: php
php:
  - 5.4

before_script:
  - npm install -g bower
  - composer self-update
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install
  - php app/console avanzu:admin:fetch-vendor

script: bin/phpunit -c app/
