language: php
sudo: required
php:
  - 5.4

before_script:
  - sudo add-apt-repository -y ppa:chris-lea/node.js
  - sudo apt-get -y update
  - sudo apt-get -y install nodejs
  - sudo npm install -g bower
  - sudo ln -s /usr/bin/bower /usr/local/bin/bower
  - composer self-update
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - touch app/data/data.db3
  - composer install
  - php app/console doctrine:schema:create --env=test
  - php app/console avanzu:admin:fetch-vendor

script: bin/phpunit -c app/
