language: php
sudo: required
php:
  - 5.4

before_script:
  - pwd
  - npm install -g bower
  - whereis bower
  - ls
  - sudo ln -s bower /usr/local/bin/bower
  - composer self-update
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - touch app/data/data.db3
  - composer install
  - php app/console doctrine:schema:create --env=test
  - php app/console avanzu:admin:fetch-vendor

script: bin/phpunit -c app/
