imports:
    - { resource: config_dev.yml }
    - { resource: security_test.yml }

framework:
    test: ~
    session:
        name: test
        storage_id: session.storage.filesystem
    profiler:
        enabled: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        default_connection: default
        driver:   pdo_sqlite
        dbname:   acs_test_db
        path:     %kernel.root_dir%/data/data.db3
        user:     test_user
        password: test_password

liip_functional_test:
    cache_sqlite_db: true
    authentication:
        username: "superadmin"
        password: "1234"
