doctrine:
    orm:
      mappings:
          gedmo_loggable:
              type: annotation
              prefix: Gedmo\Loggable\Entity
              dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
              alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
              is_bundle: false
