# Configs for the Settings Bundle
acsacs_panel_settings:
    settings_class: ACS\ACSPanelSettingsBundle\Doctrine\SettingManager
    setting_class: ACS\ACSPanelBundle\Entity\PanelSetting
    user_fields:
        # Control the version of the configuration fields
        user_schema_version:
           setting_key: user_schema_version
           label: 'User schema version'
           field_type: hidden
           default_value: '1'
           context: 'User internal'
           focus: 'user_internal'
        language:
           setting_key: user_language
           label: 'User language'
           field_type: select
           choices:
             en: 'English'
             es: 'Spanish'
             ca: 'Catalan'
             gk: 'Geek'
           default_value: 'en'
           context: 'User settings'
           focus: 'user_setting'
        theme:
           setting_key: user_theme
           label: 'Theme'
           field_type: select
           choices:
             default: 'Default'
           default_value: 'default'
           context: 'User settings'
           focus: 'user_setting'
    system_fields:
        # Control the version of the configuration fields
        system_schema_version:
           setting_key: system_schema_version
           label: 'System schema version'
           field_type: hidden
           default_value: '1'
           context: 'System internal'
           focus: 'system_internal'
        last_used_uid:
           label: 'Last Used UID (internal)'
           setting_key: last_used_uid
           field_type: hidden
           default_value: ''
           context: 'Internal'
           focus: 'internal'
        last_used_gid:
           label: 'Last Used GID (internal)'
           setting_key: last_used_gid
           field_type: hidden
           default_value: ''
           context: 'Internal'
           focus: 'internal'
        start_uid:
           label: 'First users UID'
           setting_key: start_uid
           field_type: text
           default_value: '2000'
           context: 'System settings'
           focus: 'system_setting'
        start_gid:
           label: 'First users GID'
           setting_key: start_gid
           field_type: text
           default_value: '2000'
           context: 'System settings'
           focus: 'system_setting'
        system_language:
           setting_key: system_language
           label: 'System language'
           field_type: select
           choices:
             en: 'English'
             es: 'Spanish'
             ca: 'Catalan'
           default_value: 'en'
           context: 'System settings'
           focus: 'system_setting'
        home_base:
           label: 'Home base'
           setting_key: home_base
           field_type: text
           default_value: '/home/'
           context: 'System settings'
           focus: 'system_setting'
        default_dns_service:
           label: 'Default DNS Service'
           setting_key: default_dns_service
           field_type: text
           context: 'System settings'
           focus: 'system_setting'
