# Needed bundles to work
ascacs_acspanel:
    resource: "@ACSACSPanelBundle/Resources/config/routing.yml"
    prefix:   /

ascacs_panel_users:
    resource: "@ACSACSPanelUsersBundle/Resources/config/routing.yml"
    prefix:   /

acsacs_panel_wordpress:
    resource: "@ACSACSPanelWordpressBundle/Resources/config/routing.yml"
    prefix:   /

acs_settings:
    resource: "@ACSACSPanelSettingsBundle/Resources/config/routing.yml"
    prefix:   /

# Global search action
global_search:
    pattern:  /search
    defaults: { _controller: "ACSACSPanelBundle:Default:search" }

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
