#jms_security_extra:
    #secure_all_services: false
    #expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_RESELLER:    ROLE_USER
        ROLE_ADMIN:       [ROLE_USER, ROLE_RESELLER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_SUPER_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        in_memory:
            memory:
                users:
                    superadmin: { password: 1234, roles: 'ROLE_SUPER_ADMIN' }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:
                path: /logout
                invalidate_session: false
            anonymous:    true

    access_control:
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_SUPER_ADMIN }
        - { path: ^/server, role: ROLE_ADMIN }
        - { path: ^/service, role: ROLE_ADMIN }
        - { path: ^/servicetype, role: ROLE_ADMIN }
        - { path: ^/ipaddress, role: ROLE_ADMIN }
        - { path: ^/users, role: ROLE_RESELLER }
        - { path: ^/groups, role: ROLE_ADMIN }
        - { path: ^/users, role: ROLE_RESELLER }
        - { path: ^/plans, role: ROLE_USER }
        - { path: ^/, role: ROLE_USER}
