admins:
    pattern:  /
    defaults: { _controller: "ACSACSPanelBundle:FosUser:indexAdmin" }

admins_show:
    pattern:  /{id}/show
    defaults: { _controller: "ACSACSPanelBundle:FosUser:show" }

admins_new:
    pattern:  /new
    defaults: { _controller: "ACSACSPanelBundle:FosUser:new" }

admins_create:
    pattern:  /create
    defaults: { _controller: "ACSACSPanelBundle:FosUser:create" }
    requirements: { _method: post }

admins_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ACSACSPanelBundle:FosUser:edit" }

admins_update:
    pattern:  /{id}/update
    defaults: { _controller: "ACSACSPanelBundle:FosUser:update" }
    requirements: { _method: post }

admins_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ACSACSPanelBundle:FosUser:delete" }
    requirements: { _method: post }
