database:
    pattern:  /
    defaults: { _controller: "ACSACSPanelBundle:Database:index" }

database_show:
    pattern:  /{id}/show
    defaults: { _controller: "ACSACSPanelBundle:Database:show" }

database_new:
    pattern:  /new
    defaults: { _controller: "ACSACSPanelBundle:Database:new" }

database_create:
    pattern:  /create
    defaults: { _controller: "ACSACSPanelBundle:Database:create" }
    requirements: { _method: post }

database_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ACSACSPanelBundle:Database:edit" }

database_update:
    pattern:  /{id}/update
    defaults: { _controller: "ACSACSPanelBundle:Database:update" }
    requirements: { _method: post }

database_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ACSACSPanelBundle:Database:delete" }
    requirements: { _method: post }
