db:
    path:  /
    defaults: { _controller: "ACSACSPanelBundle:DB:index" }

db_show:
    path:  /{id}/show
    defaults: { _controller: "ACSACSPanelBundle:DB:show" }

db_new:
    path:  /new
    defaults: { _controller: "ACSACSPanelBundle:DB:new" }

db_create:
    path:  /create
    defaults: { _controller: "ACSACSPanelBundle:DB:create" }
    requirements: { _method: post }

db_edit:
    path:  /{id}/edit
    defaults: { _controller: "ACSACSPanelBundle:DB:edit" }

db_update:
    path:  /{id}/update
    defaults: { _controller: "ACSACSPanelBundle:DB:update" }
    requirements: { _method: post }

db_delete:
    path:  /{id}/delete
    defaults: { _controller: "ACSACSPanelBundle:DB:delete" }
    requirements: { _method: post }
