dnsrecord:
    pattern:  /
    defaults: { _controller: "ACSACSPanelBundle:DnsRecord:index" }

dnsrecord_show:
    pattern:  /{id}/show
    defaults: { _controller: "ACSACSPanelBundle:DnsRecord:show" }

dnsrecord_new:
    pattern:  /new
    defaults: { _controller: "ACSACSPanelBundle:DnsRecord:new" }

dnsrecord_new_with_domain:
    pattern:  /{dnsdomain_id}/new
    defaults: { _controller: "ACSACSPanelBundle:DnsRecord:new" }

dnsrecord_create:
    pattern:  /create
    defaults: { _controller: "ACSACSPanelBundle:DnsRecord:create" }
    requirements: { _method: post }

dnsrecord_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ACSACSPanelBundle:DnsRecord:edit" }

dnsrecord_update:
    pattern:  /{id}/update
    defaults: { _controller: "ACSACSPanelBundle:DnsRecord:update" }
    requirements: { _method: post }

dnsrecord_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ACSACSPanelBundle:DnsRecord:delete" }
    requirements: { _method: post }
