domain:
    path:  /
    defaults: { _controller: "ACSACSPanelBundle:Domain:index" }

domain_show:
    path:  /{id}/show
    defaults: { _controller: "ACSACSPanelBundle:Domain:show" }

domain_new:
    path:  /new
    defaults: { _controller: "ACSACSPanelBundle:Domain:new" }

domain_create:
    path:  /create
    defaults: { _controller: "ACSACSPanelBundle:Domain:create" }
    requirements: { _method: post }

domain_edit:
    path:  /{id}/edit
    defaults: { _controller: "ACSACSPanelBundle:Domain:edit" }

domain_update:
    path:  /{id}/update
    defaults: { _controller: "ACSACSPanelBundle:Domain:update" }
    requirements: { _method: post }

domain_delete:
    path:  /{id}/delete
    defaults: { _controller: "ACSACSPanelBundle:Domain:delete" }
    requirements: { _method: post }

domain_search:
    path:  /search/
    defaults: { _controller: "ACSACSPanelBundle:Domain:search" }
    requirements: { _method: post }

domain_setalias:
    path:  /{id}/setalias/{type}
    defaults: { _controller: "ACSACSPanelBundle:Domain:setalias" }

domain_setenabled:
    path: /{id}/setenabled
    defaults: { _controller: "ACSACSPanelBundle:Domain:setenabled" }
