users:
    pattern:  /
    defaults: { _controller: "ACSACSPanelBundle:FosUser:index" }

users_all:
    pattern:  /all
    defaults: { _controller: "ACSACSPanelBundle:FosUser:indexAll" }

users_show:
    pattern:  /{id}/show
    defaults: { _controller: "ACSACSPanelBundle:FosUser:show" }

users_new:
    pattern:  /new
    defaults: { _controller: "ACSACSPanelBundle:FosUser:new" }

users_create:
    pattern:  /create
    defaults: { _controller: "ACSACSPanelBundle:FosUser:create" }
    requirements: { _method: post }

users_switch:
    pattern:  /{id}/swicth
    defaults: { _controller: "ACSACSPanelBundle:FosUser:switch" }

users_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ACSACSPanelBundle:FosUser:edit" }

users_update:
    pattern:  /{id}/update
    defaults: { _controller: "ACSACSPanelBundle:FosUser:update" }
    requirements: { _method: post }

users_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ACSACSPanelBundle:FosUser:delete" }
    requirements: { _method: post }

user_search:
    pattern:  /search/
    defaults: { _controller: "ACSACSPanelBundle:FosUser:search" }
    requirements: { _method: post }
