ftpduser:
    path:  /
    defaults: { _controller: "ACSACSPanelBundle:FtpdUser:index" }

ftpduser_show:
    path:  /{id}/show
    defaults: { _controller: "ACSACSPanelBundle:FtpdUser:show" }

ftpduser_new:
    path:  /new
    defaults: { _controller: "ACSACSPanelBundle:FtpdUser:new" }

ftpduser_create:
    path:  /create
    defaults: { _controller: "ACSACSPanelBundle:FtpdUser:create" }
    requirements: { _method: post }

ftpduser_edit:
    path:  /{id}/edit
    defaults: { _controller: "ACSACSPanelBundle:FtpdUser:edit" }

ftpduser_update:
    path:  /{id}/update
    defaults: { _controller: "ACSACSPanelBundle:FtpdUser:update" }
    requirements: { _method: post }

ftpduser_delete:
    path:  /{id}/delete
    defaults: { _controller: "ACSACSPanelBundle:FtpdUser:delete" }
    requirements: { _method: post }
