httpdhost:
    path:  /
    defaults: { _controller: "ACSACSPanelBundle:HttpdHost:index" }

httpdhost_grid:
    path:  /grid
    defaults: { _controller: "ACSACSPanelBundle:HttpdHost:grid" }

httpdhost_show:
    path:  /{id}/show
    defaults: { _controller: "ACSACSPanelBundle:HttpdHost:show" }

httpdhost_new:
    path:  /new
    defaults: { _controller: "ACSACSPanelBundle:HttpdHost:new" }

httpdhost_create:
    path:  /create
    defaults: { _controller: "ACSACSPanelBundle:HttpdHost:create" }
    requirements: { _method: post }

httpdhost_edit:
    path:  /{id}/edit
    defaults: { _controller: "ACSACSPanelBundle:HttpdHost:edit" }

httpdhost_update:
    path:  /{id}/update
    defaults: { _controller: "ACSACSPanelBundle:HttpdHost:update" }
    requirements: { _method: post }

httpdhost_delete:
    path:  /{id}/delete
    defaults: { _controller: "ACSACSPanelBundle:HttpdHost:delete" }
    requirements: { _method: post }

httpdhost_search:
    path:  /search/
    defaults: { _controller: "ACSACSPanelBundle:HttpdHost:search" }
    requirements: { _method: post }

httpdhost_setenabled:
    path: /{id}/setenabled
    defaults: { _controller: "ACSACSPanelBundle:HttpdHost:setenabled" }
