httpduser:
    path:  /
    defaults: { _controller: "ACSACSPanelBundle:HttpdUser:index" }

httpduser_show:
    path:  /{id}/show
    defaults: { _controller: "ACSACSPanelBundle:HttpdUser:show" }

httpduser_new:
    path:  /new
    defaults: { _controller: "ACSACSPanelBundle:HttpdUser:new" }

httpduser_create:
    path:  /create
    defaults: { _controller: "ACSACSPanelBundle:HttpdUser:create" }
    requirements: { _method: post }

httpduser_edit:
    path:  /{id}/edit
    defaults: { _controller: "ACSACSPanelBundle:HttpdUser:edit" }

httpduser_update:
    path:  /{id}/update
    defaults: { _controller: "ACSACSPanelBundle:HttpdUser:update" }
    requirements: { _method: post }

httpduser_delete:
    path:  /{id}/delete
    defaults: { _controller: "ACSACSPanelBundle:HttpdUser:delete" }
    requirements: { _method: post }

httpduser_setenabled:
    path: /{id}/setenabled
    defaults: { _controller: "ACSACSPanelBundle:HttpdUser:setenabled" }
