ipaddress:
    path:  /
    defaults: { _controller: "ACSACSPanelBundle:IpAddress:index" }

ipaddress_show:
    path:  /{id}/show
    defaults: { _controller: "ACSACSPanelBundle:IpAddress:show" }

ipaddress_new:
    path:  /new
    defaults: { _controller: "ACSACSPanelBundle:IpAddress:new" }

ipaddress_create:
    path:  /create
    defaults: { _controller: "ACSACSPanelBundle:IpAddress:create" }
    requirements: { _method: post }

ipaddress_edit:
    path:  /{id}/edit
    defaults: { _controller: "ACSACSPanelBundle:IpAddress:edit" }

ipaddress_update:
    path:  /{id}/update
    defaults: { _controller: "ACSACSPanelBundle:IpAddress:update" }
    requirements: { _method: post }

ipaddress_delete:
    path:  /{id}/delete
    defaults: { _controller: "ACSACSPanelBundle:IpAddress:delete" }
    requirements: { _method: post }

ipaddress_setenabled:
    path: /{id}/setenabled
    defaults: { _controller: "ACSACSPanelBundle:IpAddress:setenabled" }
