logitem:
    pattern:  /
    defaults: { _controller: "ACSACSPanelBundle:LogItem:index" }

logs:
    pattern:  /
    defaults: { _controller: "ACSACSPanelBundle:LogItem:index" }

logitem_search:
    pattern:  /search/
    defaults: { _controller: "ACSACSPanelBundle:LogItem:search" }
    requirements: { _method: post }

logitem_show:
    pattern:  /{id}/show
    defaults: { _controller: "ACSACSPanelBundle:LogItem:show" }

logitem_versions:
    pattern:  /{id}/versions
    defaults: { _controller: "ACSACSPanelBundle:LogItem:versions" }

logitem_update:
    pattern:  /{id}/update
    defaults: { _controller: "ACSACSPanelBundle:LogItem:update" }
    requirements: { _method: post }
