mailwblist:
    path:  /
    defaults: { _controller: "ACSACSPanelBundle:MailWBList:index" }

mailwblist_show:
    path:  /{id}/show
    defaults: { _controller: "ACSACSPanelBundle:MailWBList:show" }

mailwblist_new:
    path:  /new
    defaults: { _controller: "ACSACSPanelBundle:MailWBList:new" }

mailwblist_new_rcpt:
    path:  /new/{rcpt}/{blacklisted}
    defaults: { _controller: "ACSACSPanelBundle:MailWBList:new" }

mailwblist_new_sender:
    path:  /new/{sender}/{blacklisted}
    defaults: { _controller: "ACSACSPanelBundle:MailWBList:new" }

mailwblist_new_rcpt_sender:
    path:  /new/{rcpt}/{sender}/{blacklisted}
    defaults: { _controller: "ACSACSPanelBundle:MailWBList:new" }
    requirements:

mailwblist_create:
    path:  /create
    defaults: { _controller: "ACSACSPanelBundle:MailWBList:create" }
    requirements: { _method: post }

mailwblist_edit:
    path:  /{id}/edit
    defaults: { _controller: "ACSACSPanelBundle:MailWBList:edit" }

mailwblist_update:
    path:  /{id}/update
    defaults: { _controller: "ACSACSPanelBundle:MailWBList:update" }
    requirements: { _method: post }

mailwblist_delete:
    path:  /{id}/delete
    defaults: { _controller: "ACSACSPanelBundle:MailWBList:delete" }
    requirements: { _method: post }

mailwblist_setenabled:
    path:  /{id}/setenabled
    defaults: { _controller: "ACSACSPanelBundle:MailWBList:setenabled" }

mailwblist_setblacklisted:
    path:  /{id}/setblacklisted
    defaults: { _controller: "ACSACSPanelBundle:MailWBList:setblacklisted" }
