mailalias:
    path:  /
    defaults: { _controller: "ACSACSPanelBundle:MailAlias:index" }

mailalias_show:
    path:  /{id}/show
    defaults: { _controller: "ACSACSPanelBundle:MailAlias:show" }

mailalias_new:
    path:  /new
    defaults: { _controller: "ACSACSPanelBundle:MailAlias:new" }

mailalias_new_with_domain:
    path:  /{maildomain_id}/new
    defaults: { _controller: "ACSACSPanelBundle:MailAlias:new" }

mailalias_create:
    path:  /create
    defaults: { _controller: "ACSACSPanelBundle:MailAlias:create" }
    requirements: { _method: post }

mailalias_edit:
    path:  /{id}/edit
    defaults: { _controller: "ACSACSPanelBundle:MailAlias:edit" }

mailalias_update:
    path:  /{id}/update
    defaults: { _controller: "ACSACSPanelBundle:MailAlias:update" }
    requirements: { _method: post }

mailalias_delete:
    path:  /{id}/delete
    defaults: { _controller: "ACSACSPanelBundle:MailAlias:delete" }
    requirements: { _method: post }

mailalias_setenabled:
    path:  /{id}/setenabled
    defaults: { _controller: "ACSACSPanelBundle:MailAlias:setenabled" }
