maillogrcvd:
    path:  /
    defaults: { _controller: "ACSACSPanelBundle:MailLogrcvd:index" }

maillogrcvd_show:
    path:  /{id}/show
    defaults: { _controller: "ACSACSPanelBundle:MailLogrcvd:show" }



