maildomain:
    path:  /
    defaults: { _controller: "ACSACSPanelBundle:MailDomain:index" }

maildomain_show:
    path:  /{id}/show
    defaults: { _controller: "ACSACSPanelBundle:MailDomain:show" }

maildomain_new:
    path:  /new
    defaults: { _controller: "ACSACSPanelBundle:MailDomain:new" }

maildomain_create:
    path:  /create
    defaults: { _controller: "ACSACSPanelBundle:MailDomain:create" }
    requirements: { _method: post }

maildomain_edit:
    path:  /{id}/edit
    defaults: { _controller: "ACSACSPanelBundle:MailDomain:edit" }

maildomain_update:
    path:  /{id}/update
    defaults: { _controller: "ACSACSPanelBundle:MailDomain:update" }
    requirements: { _method: post }

maildomain_delete:
    path:  /{id}/delete
    defaults: { _controller: "ACSACSPanelBundle:MailDomain:delete" }
    requirements: { _method: post }

maildomain_setenabled:
    path: /{id}/setenabled
    defaults: { _controller: "ACSACSPanelBundle:MailDomain:setenabled" }
