mailmailbox:
    path:  /
    defaults: { _controller: "ACSACSPanelBundle:MailMailbox:index" }

mailmailbox_show:
    path:  /{id}/show
    defaults: { _controller: "ACSACSPanelBundle:MailMailbox:show" }

mailmailbox_new:
    path:  /new
    defaults: { _controller: "ACSACSPanelBundle:MailMailbox:new" }

mailmailbox_new_with_domain:
    path:  /{maildomain_id}/new
    defaults: { _controller: "ACSACSPanelBundle:MailMailbox:new" }

mailmailbox_create:
    path:  /create
    defaults: { _controller: "ACSACSPanelBundle:MailMailbox:create" }
    requirements: { _method: post }

mailmailbox_edit:
    path:  /{id}/edit
    defaults: { _controller: "ACSACSPanelBundle:MailMailbox:edit" }

mailmailbox_update:
    path:  /{id}/update
    defaults: { _controller: "ACSACSPanelBundle:MailMailbox:update" }
    requirements: { _method: post }

mailmailbox_delete:
    path:  /{id}/delete
    defaults: { _controller: "ACSACSPanelBundle:MailMailbox:delete" }
    requirements: { _method: post }

mailmailbox_setenabled:
    path: /{id}/setenabled
    defaults: { _controller: "ACSACSPanelBundle:MailMailbox:setenabled" }

mailmailbox_search:
    path:  /search/
    defaults: { _controller: "ACSACSPanelBundle:MailMailbox:search" }
    requirements: { _method: post }
