plans:
    path:  /
    defaults: { _controller: "ACSACSPanelBundle:Plan:index" }

plans_show:
    path:  /{id}/show
    defaults: { _controller: "ACSACSPanelBundle:Plan:show" }

plans_new:
    path:  /new
    defaults: { _controller: "ACSACSPanelBundle:Plan:new" }

plans_create:
    path:  /create
    defaults: { _controller: "ACSACSPanelBundle:Plan:create" }
    requirements: { _method: post }

plans_edit:
    path:  /{id}/edit
    defaults: { _controller: "ACSACSPanelBundle:Plan:edit" }

plans_update:
    path:  /{id}/update
    defaults: { _controller: "ACSACSPanelBundle:Plan:update" }
    requirements: { _method: post }

plans_delete:
    path:  /{id}/delete
    defaults: { _controller: "ACSACSPanelBundle:Plan:delete" }
    requirements: { _method: post }
