resellers:
    pattern:  /
    defaults: { _controller: "ACSACSPanelBundle:FosUser:indexReseller" }

resellers_show:
    pattern:  /{id}/show
    defaults: { _controller: "ACSACSPanelBundle:FosUser:show" }

resellers_new:
    pattern:  /new
    defaults: { _controller: "ACSACSPanelBundle:FosUser:new" }

resellers_create:
    pattern:  /create
    defaults: { _controller: "ACSACSPanelBundle:FosUser:create" }
    requirements: { _method: post }

resellers_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ACSACSPanelBundle:FosUser:edit" }

resellers_update:
    pattern:  /{id}/update
    defaults: { _controller: "ACSACSPanelBundle:FosUser:update" }
    requirements: { _method: post }

resellers_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ACSACSPanelBundle:FosUser:delete" }
    requirements: { _method: post }
