server:
    pattern:  /
    defaults: { _controller: "ACSACSPanelBundle:Server:index" }

server_show:
    pattern:  /{id}/show
    defaults: { _controller: "ACSACSPanelBundle:Server:show" }

server_new:
    pattern:  /new
    defaults: { _controller: "ACSACSPanelBundle:Server:new" }

server_create:
    pattern:  /create
    defaults: { _controller: "ACSACSPanelBundle:Server:create" }
    requirements: { _method: post }

server_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ACSACSPanelBundle:Server:edit" }

server_update:
    pattern:  /{id}/update
    defaults: { _controller: "ACSACSPanelBundle:Server:update" }
    requirements: { _method: post }

server_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ACSACSPanelBundle:Server:delete" }
    requirements: { _method: post }

server_setenabled:
    pattern: /{id}/setenabled
    defaults: { _controller: "ACSACSPanelBundle:Server:setenabled" }
