servicetype:
    path:  /
    defaults: { _controller: "ACSACSPanelBundle:ServiceType:index" }

servicetype_show:
    path:  /{id}/show
    defaults: { _controller: "ACSACSPanelBundle:ServiceType:show" }

servicetype_new:
    path:  /new
    defaults: { _controller: "ACSACSPanelBundle:ServiceType:new" }

servicetype_create:
    path:  /create
    defaults: { _controller: "ACSACSPanelBundle:ServiceType:create" }
    requirements: { _method: post }

servicetype_edit:
    path:  /{id}/edit
    defaults: { _controller: "ACSACSPanelBundle:ServiceType:edit" }

servicetype_update:
    path:  /{id}/update
    defaults: { _controller: "ACSACSPanelBundle:ServiceType:update" }
    requirements: { _method: post }

servicetype_delete:
    path:  /{id}/delete
    defaults: { _controller: "ACSACSPanelBundle:ServiceType:delete" }
    requirements: { _method: post }
