service:
    path:  /
    defaults: { _controller: "ACSACSPanelBundle:Service:index" }

service_show:
    path:  /{id}/show
    defaults: { _controller: "ACSACSPanelBundle:Service:show" }

service_new:
    path:  /new
    defaults: { _controller: "ACSACSPanelBundle:Service:new" }

service_create:
    path:  /create
    defaults: { _controller: "ACSACSPanelBundle:Service:create" }
    requirements: { _method: post }

service_edit:
    path:  /{id}/edit
    defaults: { _controller: "ACSACSPanelBundle:Service:edit" }

service_update:
    path:  /{id}/update
    defaults: { _controller: "ACSACSPanelBundle:Service:update" }
    requirements: { _method: post }

service_delete:
    path:  /{id}/delete
    defaults: { _controller: "ACSACSPanelBundle:Service:delete" }
    requirements: { _method: post }

service_setenabled:
    path: /{id}/setenabled
    defaults: { _controller: "ACSACSPanelBundle:Service:setenabled" }
