ACS\ACSPanelBundle\Entity\DatabaseUser:
    type: entity
    table: database_user
    gedmo:
        loggable: {}
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        username:
            type: string
            length: 16
            fixed: false
            nullable: false
            gedmo:
                - versioned
        password:
            type: string
            length: 250
            fixed: false
            nullable: false
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    manyToOne:
        db:
            targetEntity: DB
            nullable: false
            inversedBy: database_users
            joinColumn:
                name: database_id
                referencedColumnName: id
                onDelete: CASCADE

    lifecycleCallbacks:
      prePersist: [ ]
      postPersist: [ ]
      preUpdate: [ ]
      preRemove: [ ]

