ACS\ACSPanelBundle\Entity\DB:
    type: entity
    repositoryClass: ACS\ACSPanelBundle\Model\DBRepository
    table: db
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 64
            fixed: false
            nullable: false
        description:
            type: string
            length: 250
            fixed: false
            nullable: true
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    oneToMany:
        database_users:
            targetEntity: DatabaseUser
            mappedBy: db
            cascade: [ "persist" ]
    manyToOne:
        service:
            targetEntity: Service
            inversedBy: databases
            joinTable: null
            orderBy: null
            joinColumn:
                onDelete: CASCADE

        user:
            targetEntity: \ACS\ACSPanelUsersBundle\Entity\User
            cascade: {  }
            inversedBy: databases
            joinTable: null
            orderBy: null
            joinColumn:
                onDelete: CASCADE

    lifecycleCallbacks:
      prePersist: [ setCreatedAtValue ]
      preUpdate: [  ]
      preRemove: [ ]

