ACS\ACSPanelBundle\Entity\DnsRecord:
    type: entity
    repositoryClass: ACS\ACSPanelBundle\Model\DnsRecordRepository
    table: dns_record
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 255
            fixed: false
            nullable: true
            gedmo:
                - versioned
        type:
            type: string
            length: 6
            fixed: false
            nullable: false
            gedmo:
                - versioned
        content:
            type: string
            length: 255
            fixed: false
            nullable: true
            gedmo:
                - versioned
        ttl:
            type: integer
            unsigned: false
            nullable: true
            gedmo:
                - versioned
        prio:
            type: integer
            unsigned: false
            nullable: true
            gedmo:
                - versioned
        createdAt:
          type: datetime
          column: created_at
          gedmo:
            timestampable:
              on: create
        updatedAt:
          type: datetime
          column: updated_at
          nullable: true
          gedmo:
            timestampable:
              on: update
    manyToOne:
        dns_domain:
            targetEntity: DnsDomain
            mappedBy: dnsrecords
            cascade: [ "persist" ]
            inversedBy: dnsrecords
            joinTable: null
            orderBy: null
            gedmo:
                - versioned
            joinColumn:
                nullable: false
                onDelete: CASCADE

    lifecycleCallbacks:
      prePersist: [ setCreatedAtValue ]
      preUpdate: [ setUpdatedAtValue ]

