ACS\ACSPanelBundle\Entity\Domain:
    type: entity
    repositoryClass: ACS\ACSPanelBundle\Model\DomainRepository
    table: domain
    gedmo:
        loggable: {}
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        domain:
            type: string
            length: 255
            fixed: false
            nullable: false
            gedmo:
                - versioned
        enabled:
            type: boolean
            nullable: true
            gedmo:
                - versioned
        is_httpd_alias:
            type: boolean
            nullable: true
            gedmo:
                - versioned
        # To avoid repeat records when multiple domains point same place
        is_dns_alias:
            type: boolean
            nullable: true
            gedmo:
                - versioned
        is_mail_alias:
            type: boolean
            nullable: true
            gedmo:
                - versioned
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    manyToOne:
        user:
            targetEntity: \ACS\ACSPanelUsersBundle\Entity\User
            cascade: {  }
            inversedBy: domains
            joinTable: null
            orderBy: null
            gedmo:
                - versioned
            joinColumn:
                onDelete: CASCADE
        parent_domain:
            targetEntity: Domain
            inversedBy: child_domains
            joinColumn:
                name: parent_domain_id
                referencedColumnName: id
                onDelete: CASCADE
            gedmo:
                - versioned
    oneToMany:
        child_domains:
            targetEntity: Domain
            mappedBy: parent_domain
    oneToOne:
        httpd_host:
            targetEntity: HttpdHost
            mappedBy: domain
            gedmo:
                - versioned

    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ ]
    uniqueConstraints:
        domain_name_x:
            columns: domain

