ACS\ACSPanelBundle\Entity\IpAddress:
    type: entity
    table: ip_address
    repositoryClass: ACS\ACSPanelBundle\Model\IpAddressRepository
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        ip:
            type: string
            length: 39
            fixed: false
            nullable: false
            default: "0.0.0.0"
            gedmo:
                - versioned
        enabled:
            type: boolean
            nullable: true
            gedmo:
                - versioned
        createdAt:
          type: datetime
          column: created_at
          gedmo:
            timestampable:
              on: create
        updatedAt:
          type: datetime
          column: updated_at
          nullable: true
          gedmo:
            timestampable:
              on: update
    manyToOne:
        user:
            targetEntity: \ACS\ACSPanelUsersBundle\Entity\User
            cascade: {  }
            mappedBy: group
            inversedBy: null
            joinTable: null
            orderBy: null
            gedmo:
                - versioned
            joinColumn:
                onDelete: CASCADE
    oneToMany:
        services:
            targetEntity: Service
            mappedBy: ip
            # cascade: [ "persist" ]
    lifecycleCallbacks:
      prePersist: [ setCreatedAtValue, setDefaultValues ]
      preUpdate: [ setUpdatedAtValue ]

