ACS\ACSPanelBundle\Entity\Plan:
    type: entity
    table: plan
    gedmo:
        loggable: {}
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        planName:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: plan_name
            gedmo:
                - versioned
        maxPanelReseller:
            type: integer
            lenght: 8
            nullable: true
            column: max_panel_reseller
            gedmo:
                - versioned
        maxPanelUser:
            type: integer
            lenght: 8
            nullable: true
            column: max_panel_user
            gedmo:
                - versioned
        maxHttpdHost:
            type: integer
            lenght: 8
            nullable: true
            column: max_httpd_host
            gedmo:
                - versioned
        maxHttpdAlias:
            type: integer
            lenght: 8
            nullable: true
            column: max_httpd_alias
            gedmo:
                - versioned
        maxHttpdUser:
            type: integer
            lenght: 8
            nullable: true
            column: max_httpd_user
            gedmo:
                - versioned
        maxDomain:
            type: integer
            lenght: 8
            nullable: true
            column: max_domain
            gedmo:
                - versioned
        maxDnsDomain:
            type: integer
            lenght: 8
            nullable: true
            column: max_dns_domain
            gedmo:
                - versioned
        maxMailDomain:
            type: integer
            lenght: 8
            nullable: true
            column: max_mail_domain
            gedmo:
                - versioned
        maxMailMailbox:
            type: integer
            lenght: 8
            nullable: true
            column: max_mail_mailbox
            gedmo:
                - versioned
        maxMailAlias:
            type: integer
            lenght: 8
            nullable: true
            column: max_mail_alias
            gedmo:
                - versioned
        maxMailAliasDomain:
            type: integer
            lenght: 8
            nullable: true
            column: max_mail_alias_domain
            gedmo:
                - versioned
        maxFtpdUser:
            type: integer
            lenght: 8
            nullable: true
            column: max_ftpd_user
            gedmo:
                - versioned
        maxDb:
            type: integer
            lenght: 8
            nullable: true
            column: max_db
            gedmo:
                - versioned
        maxDbUser:
            type: integer
            lenght: 8
            nullable: true
            column: max_db_user
            gedmo:
                - versioned
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    oneToMany:
        uplans:
            targetEntity: UserPlan
            mappedBy: uplans
            cascade: [ persist ]
    lifecycleCallbacks:
      prePersist: [ setCreatedAtValue ]
      preUpdate: [ setUpdatedAtValue ]

