ACS\ACSPanelBundle\Entity\Server:
    type: entity
    table: server
    gedmo:
        loggable: {}
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        hostname:
            type: string
            length: 255
            fixed: false
            nullable: false
            gedmo:
                - versioned
        description:
            type: string
            length: 255
            gedmo:
                - versioned
        enabled:
            type: boolean
            nullable: true
            gedmo:
                - versioned
        createdAt:
          type: datetime
          column: created_at
        updatedAt:
          type: datetime
          column: updated_at
          nullable: true
    oneToMany:
        services:
            targetEntity: Service
            mappedBy: server
            #cascade: [ "persist" ]
    manyToOne:
        user:
            targetEntity: FosUser
            cascade: {  }
            mappedBy: group
            inversedBy: null
            joinTable: null
            orderBy: null
            gedmo:
                - versioned
            joinColumn:
                onDelete: RESTRICT
        ip:
            targetEntity: IpAddress
            cascade: [ "persist" ]
            inversedBy: null
            joinTable: null
            joinColumn:
                onDelete: RESTRICT
            orderBy: null
            gedmo:
                - versioned
    lifecycleCallbacks:
      prePersist: [ setCreatedAtValue ]
      preUpdate: [ setUpdatedAtValue ]

