ACS\ACSPanelBundle\Entity\ServiceType:
    repositoryClass: ACS\ACSPanelBundle\Model\ServiceTypeRepository
    type: entity
    table: service_type
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 255
            fixed: false
            nullable: false
            gedmo:
                - versioned
    manyToOne:
        parent_type:
            targetEntity: ServiceType
            cascade: {  }
            inversedBy: null
            joinTable: null
            orderBy: null
            gedmo:
                - versioned
    manyToMany:
        field_types:
            targetEntity: FieldType
            cascade: [ "persist" ]
    oneToMany:
        services:
            targetEntity: Service
            mappedBy: type

    lifecycleCallbacks: {}

